# Our Approach
This 'manifesto' is an attempt to sidestep politics, and provide a balanced approach to issues — some may argue that wanting progression for society as a whole is inherently political. 

In relation to this, our argument is that the two arms of political discourse (left vs right) is a distraction to actual progress. To place our approach on an axes is instead of looking left and right, we are looking forwards towards a better shared future. This requires approaching issues for the long-term not just the short-term.

## The General Idea
1. Approach each issue from multiple perspectives (this will likely requires contributions of different authors).
	- An attempt then will be made to try to peer-review these, find similarities and differences, to try to break down the barriers and attempt to lead to a shared perspective or shared solutions.

```{mermaid}
stateDiagram-v2

id1: Meshed Overview

Idea1 --> id1

Idea2 --> id1
```

2. There needs a way to categorise issues, and allow some of peer-review. Tagging may be along the way to a solution to categorising. Perhaps, general thoughts could be attached to a post through a new page with a unique page title, and then cross-linked at the bottom. There would obviously need to be a way to simplify or combine these comments, to avoid unnecessary bloat.

## General Philosophy
1. Simple and readable is better but not to the detriment of an idea - if an idea can be written in less words, without losing any of the essence it should be, if not then don’t lose content for the sake of simplicity. We live in a complex world.
2. Evidenced ideas are to be aimed for. While anecdotes can provide a starting point for further research, anecdotes are not evidence. This can be your own data collection and provision, in which case the tools/data should be open access. It can also mean collecting research sources, in which case more (but **relevant**) sources are better. These can be attached as footnotes.[^1], or inline depending on individual preference.

[^1]: This is an example of a reference

## Discussion
Discussion will likely be held across a number of sites until the best method for handling them makes itself known. GitHub issues provides one option, while Reddit another. We have built in [hypothes.is](https://hypothes.is) which allows direct annotation of the website, and this will link itself directly to GitHub issues. The aim is to provide the best platforms to get people involved in this project.

If in person discussions are preferred, when the project gets bigger, further methods should/could be provided. 

### Record Keeping
It would be ideal if certain conversations can occur in a markdown format (or be converted to markdown format) and therefore can be stored as an archive, especially when there are important discussions. For instance person discussions, minutes could be provided all in Markdown format making it easy to link directly to the website.

