---
title: 2025/10/31
---
  

State of manifestoforchange.org.uk as of 31 October 2025.

---

# State of the Site
This is the first blog post describing the current state of the website. Currently the content is being created and the website is being maintained all by one person (me), and therefore progress is slow outside of all my other commitments. 

I really do have a clear vision that we can have a better country and eventually a better world, but the journey towards that isn’t obvious and is riddled with complexity. 

Some questions I have been muddling over:
1. What is it that we want government to do?
2. Why does it seem to achieve so little?
3. Why do feel so little agency towards changing our system?

We have locked ourselves in a little box of convention - and instead of working towards what is good for the country, politicians end up fiddling around the edges, eking out a little growth to satiate the financial markets.

We have locked ourselves into a box of stagnation partly because there is no clear political idea of what change can look like. 

All parties promise the same, but there is no clear vision of what this change can be. 

There is nothing wrong with economic growth, in fact it is the sign of a working system, but when you are too focused on the outcome of economic growth rather then focusing on the fundamentals  of a successful society (which should generate growth), it’s like steering a bike from the back wheel.

## Next Steps:

### Content 
I need to work on a bit of a plan of which articles / pages need work. I think there is a lot of frankly rubbish that I’ve written over time, which I need to edit and cut down. 

There is also a lot of duplication and not a clear order to where pages and content should be. I want there to be a more obvious structure of posts and content on the site, and a clear vision from the front page to get to interesting content and ideas. 

Some of the content will always be a bit down the tree of pages, but I hope that with enough users, the interesting content will be surfaced as necessary.

### Getting Users / Writers / Engagement

To make this site successful it needs collaborative effort, whether this is discussion of existing articles, writing of new articles, improving the technology stack (eventually it’d be great to be closer to a Wikipedia style edit system with discussion and history built into the site).

I want to reward ideas and content, but need to work out a financial method to do this within a limited budget. 

Obviously, motivation towards writing and contributing should be driven by the right feelings - improving humanity rather than individual financial gain. 

I do also understand that content takes time to write, and those who spend time, should be able to afford to live and rewarded for hard work (just like I believe should be the case in the real world). 

With enough interaction (and some sort of polling of engaged users) there could be some method to pay a flat fee for good content. 

--- 

Please get in touch with ideas (or just a simple ‘hello’) if you are interested in the project in any way alexander-dast@pm.me
