# Digital ID
Digital ID is synonymous with authoritarian government where the target is government control over its citizens, but this isn’t the only option. It is possible to build a digital system that increases the efficiency and ease of enforcing existing laws on work and immigration, age gating content, etc. without compromising on personal agency and privacy.

It is possible to build a digital ID system where data is:
 - protected
 - siloed
 - decentralized
 - anonymised

where you can be verified for a website without the government knowing what website you are visiting and without the website knowing who you are.

This is the kind of digital ID we should want, one where it allows us to share the information we want to with the organisations we want to, where data privacy is of the highest importance, and where our information isn’t syndicated and sold.

# Data Aggregation
If each data point is separated properly with modern data security and privacy (zero-trust keys, hashing, encryption), each individual service could also aggregate its information e.g. age of the population, but would not be able to associate this information with any of the other attributes or identify of the people.

# User Control
Implementing a system like this would require informed thought about what identity parameters are necessary to enforce the law, and which are not. And which parts of the information can and should be able to be linked together.

## Example Outline
```{mermaid}
sequenceDiagram
    Alice->>+Website: Hi, I'd like to access this site.
    Website->>-Alice:You need to verify your age.
    Alice->>+gov.uk: Hi, I'm Alice.
    gov.uk->>+private.gov.uk: Here is an link to a user that has been verified.
    gov.uk->>-Alice: You are verified, await a token.
    private.gov.uk->>-Alice: Here's your anonymised key.
    Alice->>+Website: I have a  verification key.
    Website-->>+private.gov.uk: I'd like to check this key?
    private.gov.uk-->>-Website: That's valid.
    Website->-Alice: Access Granted
```

